#!/bin/bash
{
  { echo 'Updating Vim...' && 
    vim +BundleInstall +qa > /dev/tty && 
    echo 'Finished updating Vim.'
  } &&
  { 
    echo 'Updating Homebrew...' && 
    brew update && 
    brew upgrade &&
    echo 'Finished updating Homebrew.'
  } &
  { 
    echo 'Updating npm...' && 
    sudo npm update -g&& 
    echo 'Finished updating npm.'
  } &
  { echo 'Updating TeXLive...' && 
    sh ~/dotfiles/scripts/texlive_update && 
    echo 'Finished updating TeXLive.'
  }
} &&
echo 'Updated Homebrew, global npm packages, Vim plugins, and TeXLive packages!'
